export const gStatus = {
  HEALTHY : "HEALTHY",
  HUNGRY : "HUNGRY",
  THIRSTY : "THIRSTY",
  STARVING: "STARVING",
  DEHYDRATED: "DEHYDRATED",
  DEATH_BY_STARVATION: "DEATH_BY_STARVATION",
  DEATH_BY_DEHYDRATION : "DEATH_BY_DEHYDRATION",
  KILLED_BY_ANTS : "KILLED_BY_ANTS",
  KILLED_BY_HUMANS : "KILLED_BY_HUMANS",
  KILLED_BY_PREDATORS : "KILLED_BY_PREDATORS",
  CAPTURED_BY_ANTS : "CAPTURED_BY_ANTS",
  CAPTURED_BY_HUMANS : "CAPTURED_BY_HUMANS"
}
